/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAutomationRouteImport } from './routes/api/automation'
import { Route as ApiDevicesRouteImport } from './routes/api/devices'
import { Route as ApiRoomsRouteImport } from './routes/api/rooms'
import { Route as ApiAutomationIdRouteImport } from './routes/api/automation.$id'
import { Route as ApiDevicesIdRouteImport } from './routes/api/devices.$id'
import { Route as ApiDevicesIdControlRouteImport } from './routes/api/devices.$id.control'
import { Route as ApiDevicesIdToggleRouteImport } from './routes/api/devices.$id.toggle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomationRoute = ApiAutomationRouteImport.update({
  id: '/api/automation',
  path: '/api/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesRoute = ApiDevicesRouteImport.update({
  id: '/api/devices',
  path: '/api/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsRoute = ApiRoomsRouteImport.update({
  id: '/api/rooms',
  path: '/api/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomationIdRoute = ApiAutomationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAutomationRoute,
} as any)
const ApiDevicesIdRoute = ApiDevicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDevicesRoute,
} as any)
const ApiDevicesIdControlRoute = ApiDevicesIdControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => ApiDevicesIdRoute,
} as any)
const ApiDevicesIdToggleRoute = ApiDevicesIdToggleRouteImport.update({
  id: '/toggle',
  path: '/toggle',
  getParentRoute: () => ApiDevicesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/automation': typeof ApiAutomationRouteWithChildren
  '/api/devices': typeof ApiDevicesRouteWithChildren
  '/api/rooms': typeof ApiRoomsRoute
  '/api/automation/$id': typeof ApiAutomationIdRoute
  '/api/devices/$id': typeof ApiDevicesIdRouteWithChildren
  '/api/devices/$id/control': typeof ApiDevicesIdControlRoute
  '/api/devices/$id/toggle': typeof ApiDevicesIdToggleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/automation': typeof ApiAutomationRouteWithChildren
  '/api/devices': typeof ApiDevicesRouteWithChildren
  '/api/rooms': typeof ApiRoomsRoute
  '/api/automation/$id': typeof ApiAutomationIdRoute
  '/api/devices/$id': typeof ApiDevicesIdRouteWithChildren
  '/api/devices/$id/control': typeof ApiDevicesIdControlRoute
  '/api/devices/$id/toggle': typeof ApiDevicesIdToggleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/automation': typeof ApiAutomationRouteWithChildren
  '/api/devices': typeof ApiDevicesRouteWithChildren
  '/api/rooms': typeof ApiRoomsRoute
  '/api/automation/$id': typeof ApiAutomationIdRoute
  '/api/devices/$id': typeof ApiDevicesIdRouteWithChildren
  '/api/devices/$id/control': typeof ApiDevicesIdControlRoute
  '/api/devices/$id/toggle': typeof ApiDevicesIdToggleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/automation'
    | '/api/devices'
    | '/api/rooms'
    | '/api/automation/$id'
    | '/api/devices/$id'
    | '/api/devices/$id/control'
    | '/api/devices/$id/toggle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/automation'
    | '/api/devices'
    | '/api/rooms'
    | '/api/automation/$id'
    | '/api/devices/$id'
    | '/api/devices/$id/control'
    | '/api/devices/$id/toggle'
  id:
    | '__root__'
    | '/'
    | '/api/automation'
    | '/api/devices'
    | '/api/rooms'
    | '/api/automation/$id'
    | '/api/devices/$id'
    | '/api/devices/$id/control'
    | '/api/devices/$id/toggle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAutomationRoute: typeof ApiAutomationRouteWithChildren
  ApiDevicesRoute: typeof ApiDevicesRouteWithChildren
  ApiRoomsRoute: typeof ApiRoomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automation': {
      id: '/api/automation'
      path: '/api/automation'
      fullPath: '/api/automation'
      preLoaderRoute: typeof ApiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices': {
      id: '/api/devices'
      path: '/api/devices'
      fullPath: '/api/devices'
      preLoaderRoute: typeof ApiDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms': {
      id: '/api/rooms'
      path: '/api/rooms'
      fullPath: '/api/rooms'
      preLoaderRoute: typeof ApiRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automation/$id': {
      id: '/api/automation/$id'
      path: '/$id'
      fullPath: '/api/automation/$id'
      preLoaderRoute: typeof ApiAutomationIdRouteImport
      parentRoute: typeof ApiAutomationRoute
    }
    '/api/devices/$id': {
      id: '/api/devices/$id'
      path: '/$id'
      fullPath: '/api/devices/$id'
      preLoaderRoute: typeof ApiDevicesIdRouteImport
      parentRoute: typeof ApiDevicesRoute
    }
    '/api/devices/$id/control': {
      id: '/api/devices/$id/control'
      path: '/control'
      fullPath: '/api/devices/$id/control'
      preLoaderRoute: typeof ApiDevicesIdControlRouteImport
      parentRoute: typeof ApiDevicesIdRoute
    }
    '/api/devices/$id/toggle': {
      id: '/api/devices/$id/toggle'
      path: '/toggle'
      fullPath: '/api/devices/$id/toggle'
      preLoaderRoute: typeof ApiDevicesIdToggleRouteImport
      parentRoute: typeof ApiDevicesIdRoute
    }
  }
}

interface ApiAutomationRouteChildren {
  ApiAutomationIdRoute: typeof ApiAutomationIdRoute
}

const ApiAutomationRouteChildren: ApiAutomationRouteChildren = {
  ApiAutomationIdRoute: ApiAutomationIdRoute,
}

const ApiAutomationRouteWithChildren = ApiAutomationRoute._addFileChildren(
  ApiAutomationRouteChildren,
)

interface ApiDevicesIdRouteChildren {
  ApiDevicesIdControlRoute: typeof ApiDevicesIdControlRoute
  ApiDevicesIdToggleRoute: typeof ApiDevicesIdToggleRoute
}

const ApiDevicesIdRouteChildren: ApiDevicesIdRouteChildren = {
  ApiDevicesIdControlRoute: ApiDevicesIdControlRoute,
  ApiDevicesIdToggleRoute: ApiDevicesIdToggleRoute,
}

const ApiDevicesIdRouteWithChildren = ApiDevicesIdRoute._addFileChildren(
  ApiDevicesIdRouteChildren,
)

interface ApiDevicesRouteChildren {
  ApiDevicesIdRoute: typeof ApiDevicesIdRouteWithChildren
}

const ApiDevicesRouteChildren: ApiDevicesRouteChildren = {
  ApiDevicesIdRoute: ApiDevicesIdRouteWithChildren,
}

const ApiDevicesRouteWithChildren = ApiDevicesRoute._addFileChildren(
  ApiDevicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAutomationRoute: ApiAutomationRouteWithChildren,
  ApiDevicesRoute: ApiDevicesRouteWithChildren,
  ApiRoomsRoute: ApiRoomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
