/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDevicesRouteImport } from './routes/api/devices'
import { Route as ApiRoomsRouteImport } from './routes/api/rooms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesRoute = ApiDevicesRouteImport.update({
  id: '/api/devices',
  path: '/api/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsRoute = ApiRoomsRouteImport.update({
  id: '/api/rooms',
  path: '/api/rooms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/devices': typeof ApiDevicesRoute
  '/api/rooms': typeof ApiRoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/devices': typeof ApiDevicesRoute
  '/api/rooms': typeof ApiRoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/devices': typeof ApiDevicesRoute
  '/api/rooms': typeof ApiRoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/devices' | '/api/rooms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/devices' | '/api/rooms'
  id: '__root__' | '/' | '/api/devices' | '/api/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDevicesRoute: typeof ApiDevicesRoute
  ApiRoomsRoute: typeof ApiRoomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices': {
      id: '/api/devices'
      path: '/api/devices'
      fullPath: '/api/devices'
      preLoaderRoute: typeof ApiDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms': {
      id: '/api/rooms'
      path: '/api/rooms'
      fullPath: '/api/rooms'
      preLoaderRoute: typeof ApiRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDevicesRoute: ApiDevicesRoute,
  ApiRoomsRoute: ApiRoomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
